name: Delete Branch

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          branch=${{ github.event.pull_request.head.ref }}
          git push origin --delete "$branch"
